// components/headers.js
import React from 'react';
import {ASCII_ART} from './asciiart';

export const HeaderImage = () => (
  <div className="header-image">
    <ASCII_ART />
    <div className="header-text">
      <h1 className="header-title">i am james</h1>
      <p className="header-subtitle">
        "ai/ml engineer" crafting innovative solutions at ▒▒▒▒▒▒▒▒▒▒.
      </p>
      <p className="header-footer">
        <em>
          "The mastermind behind <a href="https://www.example.com" className="marutech-link"> MaruTech AI</a>, an AI/ML service line dedicated to creating custom solutions for your needs!"
        </em>
      </p>
    </div>
  </div>
);

export const HeaderLine = () => (
  <div className="header-line">
    <div className="running-text">
      UI generated by Claude 3.5 Sonnet • UX/UI is my kryptonite UI •
      UI generated by Claude 3.5 Sonnet • UX/UI is my kryptonite UI • 
      UI generated by Claude 3.5 Sonnet • UX/UI is my kryptonite UI • 
      UI generated by Claude 3.5 Sonnet • UX/UI is my kryptonite UI
    </div>
  </div>
);
